name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to surge.sh
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'yvr.builders'
          project: '.'
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}
